config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :presentations do
    resources :participations, only: [:update]
    resources :surveys do
      resources :questions
    end
    resources :responses, only: [:index, :new, :create]
    resources :survey_generations, only: [:create]
  end

  resources :survey_templates do
    resources :question_templates
  end

  resources :user_generations, only: [:index, :new, :create]
end

app/views/shared/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <strong>Success!</strong> <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <strong>Warning!</strong> <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer footer-padding">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <h4>Site Map</h4>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <% if current_user %>
          <li><%= link_to 'Presentations', presentations_path %></li>
          <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-sm-4">
        <h4>Follow us:</h4>
        <ul>
          <li><%= link_to 'LinkedIn', 'https://www.linkedin.com/company/excella-consulting' %></li>
          <li><%= link_to 'Twitter', 'https://twitter.com/ExcellaCo' %></li>
          <li><%= link_to 'Facebook', 'https://www.facebook.com/excellaconsulting/' %></li>
        </ul>
      </div>
      <div class="col-sm-4">
        <h4><%= link_to 'Excella Consulting', 'https://www.excella.com/' %></h4>
        <p>2300 Wilson Boulevard, Suite 630<br />Arlington, VA 22201</p>
        <h5>&copy; Excella Consulting, 2017</h5>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag("Excella Logo Full Color.png", alt: "Excella Consulting") %>
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "View Presentations", presentations_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <% if current_user.is_admin %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create New User", new_user_generation_path %></li>
            <li><%= link_to "Create New Presentation", new_presentation_path %></li>
            <li><%= link_to "See Survey Templates", survey_templates_path %></li>
          </ul>
        </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Hi, #{current_user.first_name.capitalize}"%> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/shared/_question_form.html.erb
<%= error_messages(question) %>

<%= form_for(question, url: submit_path) do |f| %>
  <% if question.methods.include?(:position) %>
  <div class="form-group">
    <%= f.label :position %>
    <%= f.number_field :position, class: "form-control" %>
  </div>
  <% end %>

  <div class="form-group <%= error_class(question, :prompt) %>">
    <%= f.label :prompt %>
    <%= f.text_field :prompt, class: "form-control" %>
  </div>

  <div class="form-group <%= error_class(question, :response_type) %>">
    <%= f.label :response_type, "Response Type" %>
    <%= f.select :response_type,
      options_for_select([['Number', 'number'], ['Text', 'text']], selected: f.object.response_type),
      { include_blank: true }, class: "form-control"  %>
  </div>

  <div class="form-group <%= error_class(question, :response_required) %>">
    <%= f.label :response_required, "Response Required" %>
    <br>
    <%= f.radio_button :response_required, true %> True
    <%= f.radio_button :response_required, false %> False
  </div>

  <%= f.submit "Submit", class: "btn btn-primary"  %>
  <%= link_to "Cancel", :back, class: "btn btn-default" %>
<% end %>