config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :presentations do
    resources :participations, only: [:update]
    resources :surveys do
      resources :questions
    end
    resources :responses, only: [:index, :new, :create]
    resources :survey_generations, only: [:create]
  end

  resources :survey_templates do
    resources :question_templates
  end

  resources :user_generations, only: [:index, :new, :create]
end

app/models/survey.rb
#
# Survey model
#
class Survey < ApplicationRecord
  belongs_to :presentation

  #
  # acts_as_list gem handles Survey order based on parent Presentation
  #
  acts_as_list scope: :presentation

  has_many :questions, dependent: :destroy

  validates :title, :position, presence: true

  #
  # Normalize survey positions for a presentation so they are in sequential order
  #
  def self.normalize_position(presentation)
    presentation.surveys.order(:position).each_with_index do |survey, index|
      survey.position = index + 1
      survey.save
    end
  end

  #
  # Get the highest survey position for a presentation
  #
  def self.highest_position(presentation)
    presentation.surveys.maximum(:position) || 0
  end

  #
  # Build unsaved survey from presentation & survey template
  #
  def self.build_from_template(survey_template, presentation)
    presentation.surveys.new(
      title: survey_template.title,
      position: Survey.highest_position(presentation) + 1
    )
  end
end

app/controllers/surveys_controller.rb
#
# SurveysController
#
class SurveysController < ApplicationController
  before_action :authenticate_admin_or_presenter, except: :show
  before_action :set_presentation

  #
  # Index route
  #
  def index
    @surveys = @presentation.surveys.order(:position)
  end

  #
  # New route
  #
  def new
    @survey = @presentation.surveys.new
  end

  #
  # Create route
  #
  def create
    @survey = @presentation.surveys.new(survey_params)
    save_survey
  end

  #
  # Show route
  #
  def show
    @survey = Survey.find(params[:id])
    @questions = @survey.questions.order(:position)
  end

  #
  # Edit route
  #
  def edit
    @survey = Survey.find(params[:id])
  end

  #
  # Update route
  #
  def update
    @survey = Survey.find(params[:id])
    update_survey
  end

  #
  # Destroy route
  #
  def destroy
    @survey = Survey.find(params[:id])
    destroy_survey
  end

  private

  #
  # Set and sanitize survey params
  #
  def survey_params
    params.require(:survey).permit(:presentation_id, :title, :position)
  end

  #
  # Set presentation to be used in routes
  #
  def set_presentation
    @presentation = Presentation.find(params[:presentation_id])
  end

  #
  # Save helper for create action
  #
  def save_survey
    if @survey.save
      Survey.normalize_position(@presentation)

      flash[:success] = success_message(@survey, :create)
      redirect_to presentation_survey_path(@presentation.id, @survey.id)
    else
      flash.now[:error] = error_message(@survey, :create)
      render :new
    end
  end

  #
  # Update helper for update action
  #
  def update_survey
    if @survey.update(survey_params)
      Survey.normalize_position(@presentation)

      flash[:success] = success_message(@survey, :update)
      redirect_to presentation_survey_path(@presentation.id, @survey.id)
    else
      flash.now[:error] = error_message(@survey, :create)
      render :edit
    end
  end

  #
  # Destroy helper for destroy action
  #
  def destroy_survey
    if @survey.destroy
      flash[:success] = success_message(@survey, :delete)
      redirect_to presentation_surveys_path
    else
      flash[:error] = error_message(@question, :delete)
      redirect_back fallback_location: presentation_survey_path(@presentation.id, @survey.id)
    end
  end
end

app/helpers/surveys_helper.rb
#
# SurveysHelper
#
module SurveysHelper
  #
  # Renders options/links for Presentation show page
  #
  def new_survey_action_button(user, presentation)
    participation = Participation.where(user_id: user.id, presentation_id: presentation.id).first

    return unless user.is_admin || participation.is_presenter
    content_tag :div, class: 'admin-options' do
      link_to 'Create New Survey', new_presentation_survey_path(presentation), class: 'btn btn-primary'
    end
  end

  #
  # Renders controller action links for index page
  #
  def survey_option_buttons(survey)
    content_tag :div, class: 'admin-options' do
      edit_button = link_to 'Edit Survey',
                            edit_presentation_survey_path(@presentation, survey),
                            class: "btn btn-primary #{disable_check(survey, current_user)}"
      delete_button = link_to 'Delete Survey',
                              presentation_survey_path(@presentation, survey),
                              class: "btn btn-danger #{disable_check(survey, current_user)}",
                              method: :delete,
                              data: { confirm: 'Are you sure you want to delete this item?' }

      edit_button + delete_button
    end
  end

  #
  # Returns css class to disable links if survey is for a different presenter
  #
  def disable_check(survey, user)
    return if survey.presenter_id.nil? || user.is_admin || survey.presenter_id == user.id
    'disabled'
  end

  #
  # Return a confirmation message data object if a survey template title matches a survey
  #
  def duplicate_confirm(survey_template, surveys)
    survey_titles = surveys.pluck(:title).map(&:downcase)

    return unless survey_titles.include?(survey_template.title.downcase)
    { confirm: "A survey with this title already exists. Are you sure you want to add another \"#{survey_template.title}\"?" }
  end
end

app/views/surveys/_form.html.erb
<%= error_messages(@survey) %>

<%= form_for ([@presentation, @survey]) do |f| %>
  <div class="form-group">
    <%= f.label :position %>
    <%= f.number_field :position, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_area :title, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", :back, class: "btn btn-default" %>
<% end %>

app/views/surveys/edit.html.erb
<div class="container">
  <%= back_button %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2">
      <h1>Edit Survey</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/surveys/index.html.erb
<div class="container">
  <%= back_button(presentation_path(@presentation)) %>

  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 text-center">
      <%= new_survey_action_button(current_user, @presentation) %>
      <h1 class="text-center">Surveys</h1>
      <%= content_tag :div, id: 'survey-presentations', class: "panel panel-warning text-left" do %>
      <div class="panel-heading">
        <h4><%= @presentation.title %></h4>
      </div>
      <table class="table">
        <tr>
          <th>Title</th>
          <th>Actions</th>
        </tr>
        <% @surveys.each do |survey| %>
        <tr>
          <td><%= link_to "(#{survey.position}) #{survey.title}", presentation_survey_path(@presentation.id, survey.id), class: disable_check(survey, current_user) %></td>
          <td>
            <%= survey_option_buttons(survey) %>
          </td>
        </tr>
        <% end %>
      </table>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 text-center">
      <%= content_tag :div, class: "panel panel-info text-left" do %>
      <div class="panel-heading">
        <h4>Survey Templates</h4>
      </div>
      <table class="table">
        <% SurveyTemplate.all.each_with_index do |survey_template, index| %>
        <tr>
          <td class="survey-template-presentation">
            <div class="title">
              <a class="glyphicon glyphicon-chevron-right" aria-hidden="true" role="button" data-id="<%= index %>"></a>
              <%= survey_template.title %>
            </div>
            <div class="action">
              <%= link_to "Add to Presentation", presentation_survey_generations_path(@presentation, survey_template_id: survey_template.id), method: :post, data: duplicate_confirm(survey_template, @surveys) %>
            </div>
            <table class="table table-bordered question-table" data-id="<%= index %>">
              <tr>
                <th class="col-xs-6">Questions on Survey</th>
                <th class="col-xs-4">Response Type</th>
                <th class="col-xs-2">Required?</th>
              </tr>
              <% survey_template.question_templates.each do |question_template| %>
              <tr>
                <td class="col-xs-6"><%= question_template.prompt %></td>
                <td class="col-xs-4"><%= question_template.response_type.capitalize %></td>
                <td class="col-xs-2"><%= required_check(question_template) %></td>
              </tr>
              <% end %>
            </table>
          </td>
        </tr>
        <% end %>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/surveys/new.html.erb
<div class="container">
  <%= back_button %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2">
      <h1>New Survey</h1>
      <%= render 'form', survey: @survey %>
    </div>
  </div>
</div>

app/views/surveys/show.html.erb
<div class="container">
  <%= back_button(presentation_surveys_path(@presentation)) %>
  <div class="row">
    <div class="col-md-12 text-center">
      <%= survey_option_buttons(@survey) %>
      <h1 class="text-center"><%= @survey.title %> Survey for '<%= @presentation.title %>'</h1>
    </div>
  </div>
  <!-- /.row -->

  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
      <%= link_to 'Add a Question',
          new_presentation_survey_question_path(@presentation, @survey),
          submit_path: presentation_survey_questions_path(@presentation, @survey),
          class: "btn btn-success"%>
      <hr />
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><strong>Survey Title:</strong> <%= @survey.title %></h4>
        </div>
        <div class="table-responsive">
          <table class="table table-striped">
            <tr>
              <th>Questions on Survey</th>
              <th>Response Type</th>
              <th>Required?</th>
              <th>Actions</th>
            </tr>
            <% @questions.each do |question| %>
            <tr>
              <td>(<%= question.position %>) <%= question.prompt %></td>
              <td><%= question.response_type.capitalize %></td>
              <td><%= required_check(question) %></td>
              <td><%= action_buttons(edit_path: edit_presentation_survey_question_path(@presentation, @survey, question),
                                     delete_path: presentation_survey_question_path(@presentation, @survey, question)) %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->
</div>
<!--- /.container -->