config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :presentations do
    resources :participations, only: [:update]
    resources :surveys do
      resources :questions
    end
    resources :responses, only: [:index, :new, :create]
    resources :survey_generations, only: [:create]
  end

  resources :survey_templates do
    resources :question_templates
  end

  resources :user_generations, only: [:index, :new, :create]
end

app/models/survey_template.rb
#
# SurveyTemplate model
#
class SurveyTemplate < ApplicationRecord
  has_many :question_templates, dependent: :destroy

  validates :title, :name, presence: true
end

app/controllers/survey_templates_controller.rb
#
# SurveyTemplatesController
#
class SurveyTemplatesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :set_survey_template, only: [:show, :edit, :update, :destroy]

  #
  # Render Survey Template data
  #
  def index
    @survey_templates = SurveyTemplate.all
  end

  #
  # Show route
  #
  def show
  end

  #
  # New route
  #
  def new
    @survey_template = SurveyTemplate.new
  end

  #
  # Create route
  #
  def create
    @survey_template = SurveyTemplate.new(survey_template_params)
    create_survey_template
  end

  #
  # Edit route
  #
  def edit
  end

  #
  # Update route
  #
  def update
    update_survey_template
  end

  #
  # Destroy route
  #
  def destroy
    destroy_survey_template
  end

  private

  #
  # Set survey_template to be used in routes
  #
  def set_survey_template
    @survey_template = SurveyTemplate.find(params[:id])
  end

  #
  # Set and sanitize survey params
  #
  def survey_template_params
    params.require(:survey_template).permit(:title, :name)
  end

  #
  # Logic helper for create action
  # Extrapolated into new method to appease Rubocop
  #
  def create_survey_template
    if @survey_template.save
      flash[:success] = success_message(@survey_template, :create)
      redirect_to survey_template_path(@survey_template)
    else
      flash.now[:error] = error_message(@survey_template, :create)
      render :new
    end
  end

  #
  # Logic helper for update action
  # Extrapolated into new method to appease Rubocop
  #
  def update_survey_template
    if @survey_template.update(survey_template_params)
      flash[:success] = success_message(@survey_template, :update)
      redirect_to @survey_template, notice: 'Survey Template was successfully updated.'
    else
      flash.now[:error] = error_message(@survey_template, :update)
      render :edit
    end
  end

  #
  # Logic helper for destroy action
  # Extrapolated into new method to appease Rubocop
  #
  def destroy_survey_template
    if @survey_template.destroy
      flash[:success] = success_message(@survey_template, :delete)
      redirect_to survey_templates_url, notice: 'Survey Template was successfully destroyed.'
    else
      flash[:error] = error_message(@survey_template, :delete)
      redirect_back fallback_location: survey_templates_path
    end
  end
end

app/helpers/survey_templates_helper.rb
#
# SurveyTemplatesHelper
#
module SurveyTemplatesHelper
  #
  # Renders action links for survey templates
  #
  def action_buttons(edit_path:, delete_path:)
    edit_link = link_to 'Edit', edit_path, class: 'btn btn-primary'
    delete_link = link_to 'Delete', delete_path, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure you want to delete this item?' }

    edit_link + delete_link
  end

  #
  # Checks if questions_template is required and returns formatted response for table
  #
  def required_check(questions_template)
    questions_template.response_required ? '✓' : ''
  end

  #
  # Renders link to create new survey template
  #
  def new_survey_template_link
    link_to 'New Survey Template', new_survey_template_path, class: 'btn btn-success'
  end

  #
  # Renders controller action links for show page
  #
  def survey_template_options
    content_tag :div, class: 'admin-options' do
      edit_link = link_to 'Edit Survey', edit_survey_template_path(@survey_template), class: 'btn btn-primary'
      delete_link = link_to 'Delete Survey', survey_template_path(@survey_template), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure you want to delete this item?' }

      edit_link + delete_link
    end
  end
end

app/views/survey_templates/_form.html.erb
<%= error_messages(survey_template) %>

<%= form_for(survey_template) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <em>(Name of Template for internal organization)</em>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    <em>(Title of Survey to display to all users)</em>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary"  %>
  <%= link_to "Cancel", :back, class: "btn btn-default" %>
<% end %>

app/views/survey_templates/edit.html.erb
<div class="container">
  <%= back_button %>

  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2">
      <h1>Edit Survey Template</h1>
      <%= render 'form', survey_template: @survey_template %>
    </div>
  </div>
</div>

app/views/survey_templates/index.html.erb
<div class="container">
  <%= back_button(presentations_path) %>

  <div class="row">
    <div class="col-md-12 text-center spaceMdBtm">
      <h1>Survey Templates</h1>
      <%= new_survey_template_link %>
    </div>
  </div>
  <!-- /.row -->

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>All Templates</h4>
        </div>
        <div class="table-responsive">
          <table class="table table-striped">
            <tr>
              <th>Template Name</th>
              <th>Actions</th>
            </tr>
            <% @survey_templates.each do |survey_template| %>
            <tr>
              <td><%= link_to survey_template.name, survey_template_path(survey_template) %></td>
              <td><%= action_buttons(edit_path: edit_survey_template_path(survey_template),
                                     delete_path: survey_template_path(survey_template)) %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->

</div>
<!--- /.container -->

app/views/survey_templates/new.html.erb
<div class="container">
  <%= back_button(survey_templates_path) %>

  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2">
      <h1>New Survey Template</h1>
      <%= render 'form', survey_template: @survey_template %>
    </div>
  </div>
</div>

app/views/survey_templates/show.html.erb
<div class="container">
  <%= back_button(survey_templates_path) %>
  <div class="row">
    <div class="col-md-12 text-center">
      <%= survey_template_options %>
      <h1 class="text-center"><%= @survey_template.name %></h1>
    </div>
  </div>
  <!-- /.row -->

  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
      <%= link_to 'Add a Question', new_survey_template_question_template_path(@survey_template), class: "btn btn-success"%>
      <hr />
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="alert alert-info">
        <i>From this screen, you can view and edit your Survey Template: <strong>&quot;<%= @survey_template.name %>&quot;</strong>.</i>
        <hr />
        <i>Note that &quot;Survey Title&quot; represents what the End User will see when filling out this survey.</i>
      </div>
    </div>
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><strong>Survey Title:</strong> <%= @survey_template.title %></h4>
        </div>
        <div class="table-responsive">
          <table class="table table-striped">
            <tr>
              <th>Questions on Survey</th>
              <th>Response Type</th>
              <th>Required?</th>
              <th>Actions</th>
            </tr>
            <% @survey_template.question_templates.each do |question_template| %>
            <tr>
              <td><%= question_template.prompt %></td>
              <td><%= question_template.response_type.capitalize %></td>
              <td><%= required_check(question_template) %></td>
              <td><%= action_buttons(edit_path: edit_survey_template_question_template_path(@survey_template, question_template),
                                     delete_path: survey_template_question_template_path(@survey_template, question_template)) %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->

</div>
<!--- /.container -->